# Generated by Django 2.2.1 on 2020-07-30 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20200730_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='scraped_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bot.Workers'),
        ),
    ]
