# Generated by Django 2.2.1 on 2020-07-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_members_scraped_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='adding_permision',
            field=models.BooleanField(default=True),
        ),
    ]
