# Generated by Django 2.2.1 on 2020-08-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_members_member_source_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
