# Generated by Django 2.2.1 on 2020-09-03 14:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_workers_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='worker_source_groups',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
    ]
